unit ResultCode;

interface

const
  ERROR_SUCCESS = 0;
  ERROR_FILE_NOT_FOUND = 1001;
  ERROR_FILE_NOT_FOUND_MSG = '文件不存在';
  ERROR_SERVICE_EXIST = 1002;
  ERROR_SERVICE_EXIST_MSG = '服务已存在';
  ERROR_SERVICE_DONT_NOT_EXIST = 1003;
  ERROR_SERVICE_DONT_NOT_EXIST_MSG = '服务不存在';
  ERROR_SERVICE_NOT_ACTIVE = 1004;
  ERROR_SERVICE_NOT_ACTIVE_MSG = '服务没有激活';
  ERROR_SERVICE_DISABLED = 1005;
  ERROR_SERVICE_DISABLED_MSG = '服务被禁用';
  ERROR_PLUGIN_CONFIG_DOES_NOT_EXIST = 1006;
  ERROR_PLUGIN_CONFIG_DOES_NOT_EXIST_MSG = '插件在配置文件中不存在';
  ERROR_PLUGIN_DISABLED = 1007;
  ERROR_PLUGIN_DISABLED_MSG = '插件被禁用';
  ERROR_NOT_PLUGIN_DLL = 1008;
  ERROR_NOT_PLUGIN_DLL_MSG = '不是合法的插件模块';
  ERROR_INTERFACE_IS_NULL = 1009;
  ERROR_INTERFACE_IS_NULL_MSG = '接口对象为空';
  ERROR_UNLOAD_PLUGIN_FAIL = 1010;
  ERROR_UNLOAD_PLUGIN_FAIL_MSG = '卸载插件失败';
  ERROR_OUT_BOUND = 1011;
  ERROR_OUT_BOUND_MSG = '数组访问越界';
  ERROR_PLUGIN_DONT_NOT_EXIST = 1012;
  ERROR_NOT_LOAD_PLUGIN_DLL = 1013;
  ERROR_NOT_LOAD_PLUGIN_DLL_MSG = '没有载入插件DLL';

implementation

end.
